### ISSUE TITLE
Yap speed improvements

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-iOS#11]
- [x] Load 1 day of events at a time

**Comment by chrisballinger** [comment]
We already do this, but there are other things we could probably improve.

**Comment by OnlyInAmerica** [comment]
I think there are still wins to be made here. Some benchmarks from an iPhone 6+

From touching the icon to onboard appearing : ~6sec
After onboarding I touch "Events", then "Sunday 9/6" and it takes ~**40sec** for events to appear.

**Comment by chrisballinger** [comment]
The startup speed is unaffected by Yap and is mainly caused by loading the tiles. However the 40s for events to load should be improved. I've noticed inconsistent performance where sometimes it's fast and others it takes forever. It could be sped up by removing the type and expiration filtering feature... but I don't see any easy ways to speed it up the way it's currently designed.
